name: Sync Docs Data

on:
  schedule:
    # Run every 6 hours (at 1:00, 7:00, 13:00, 19:00 UTC)
    - cron: '1 */6 * * *'
  workflow_dispatch:

jobs:
  sync-Expert-Consensus-with-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Copy JSON files to docs/data
        run: |
          mkdir -p docs/data
          cp Player-Context/Expert-Consensus/*.json docs/data/
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/data/
          git diff --staged --quiet || git commit -m "Auto-sync: Update data files from Player-Context"
          git push
